scylladb/scylladb-web-install

server

Removing "apt-transport-https" package installation in case of Ubuntu 16.04.
Only curl and gnupg2 packages will be installed for all Ubuntu version.

Remove "apt-transport-https" package installation for Ubuntu 16.04

---

server

The "7"|8.? case in centos checks version changed to 7*|8* to allow scylla installation on centos8, rocky8.* and etc.

Fix to able to install scylla on CentOS8

---

server

Adding seperate function of curl and gpg packages installation for Ubuntu and Debian.
Removing "apt-transport-https" and "dirmngr" installation in case of Debian OS.
"user input", "check_os" and "os-release" checks order were changed.

Fix curl issue + change checks order

---

server

After removing "dirmngr" and "apt-transport-https" packages (#44) - the installation process for Debian and Ubuntu become the same. Therefore the funtcions were merged.

merge ubuntu and debian install functions

---

.github/workflows/test.yml

Followng the fix in: #40 , the github-actions test was updated. The tests for first release will be run on all supported OSs.
Also added test for ubuntu for latest version in specific version indication.
Closes: #42

update github-actions test - to support tests for first release and latest in specific version

---

.github/workflows/test.yml
server

fix for installing nightly-master version, instead of cut specific version using awk.
Adding test for nightly-master version in github-actions (test.yml)

server: fix for installing nightly-master version + github-actions: adding nightly-master version test

---

server

In one of my debug sessions i got the following error:
```
[2022-06-07T06:21:59.928Z] Installing Scylla version nightly-master for Red Hat Enterprise Linux ...
[2022-06-07T06:22:04.092Z] Status code: 403 for https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm (IP: 38.145.60.24)
[2022-06-07T06:22:04.654Z] Error: error building at STEP "RUN ./server.sh $SCYLLA_PRODUCT_NAME $SCYLLA_VERSION $DRY_RUN $SCYLLA_REPO_FILE_URL": error while running runtime: exit status 1
script returned exit code 125
```
It seems that `epel` is not needed for the installation, so let's remove it

server:remove epel installation from rhel and oracle

---

server

Following the work done in https://github.com/scylladb/scylladb/pull/10957 , adding the support for new convention for `rc` releases
related: https://github.com/scylladb/scylla-pkg/pull/3007

server:Add support to new version convention

---

server

As part of the apt-key deprecation [0], we need to use gpg to consume the
repo key and change the repo file (scylla.list) to explicitly point
to the key,
We'll start with adding the gpg and later remove the apt-key ref
Ref https://github.com/scylladb/scylladb/issues/11186
[0] https://wiki.debian.org/DebianRepository/UseThirdParty

deb: move from apt-key command to gpg

---

.github/workflows/test.yml

4.5.0 was removed. web installation for 5.0.0 and 2022.1.0 were added.

update versions in ci tests

---

server

commit: **fd9f6ee**
changes in grep command to get a "fixed" string instead of a regular expression pattern - fix for:
root@701da59c56cc:/scylla-web-install# apt-cache madison scylla | grep 5.0.2
scylla | **5.0.2**-0.20220807.299122e78-1 | http://downloads.scylladb.com/downloads/scylla/deb/debian-ubuntu/scylladb-5.0 stable/main amd64 Packages
scylla | 5.0~rc**5-0.2**0220515.9da666e77-1 | http://downloads.scylladb.com/downloads/scylla/deb/debian-ubuntu/scylladb-5.0 stable/main amd64 Packages
commit : **7865d9a**
node-exporter dependency package was added to the scylla-enterprise installation started from version 2022.X

change grep command in getting FULL_SCYLLA_VERSION

---

server

During debug session noticed the following error:
```
[2022-11-06T08:49:29.493Z] E: Failed to fetch http://deb.debian.org/debian/pool/main/p/perl/perl-modules-5.28_5.28.1-6+deb10u1_all.deb  Cannot initiate the connection to deb.debian.org:80 (2a04:4e42:62::644). - connect (101: Network is unreachable) Could not connect to deb.debian.org:80 (199.232.138.132), connection timed out
.
.
.
[2022-11-06T08:49:29.500Z] E: Failed to fetch http://deb.debian.org/debian/pool/main/x/xdg-user-dirs/xdg-user-dirs_0.17-2_amd64.deb  Cannot initiate the connection to deb.debian.org:80 (2a04:4e42:62::644). - connect (101: Network is unreachable)
[2022-11-06T08:49:29.500Z] E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
Re-build is working. let's retry `apt-get …

server: add Retries when running `apt-get update`

---

server

The 2022 key remains for the period of time between the addition of the new pub key and the time we start singing with the 2024 key, later we can remove it.

gpg: add the 2024 pub key

---

server

Fixes: https://github.com/scylladb/scylladb-web-install/issues/64

web-install: add ubuntu24.04 support

---

server

During 6.0 i saw the following faliure:
```
[2024-05-23T08:34:29.061Z] Red Hat Enterprise Linux 8.10 is not supported by this installer.
[2024-05-23T08:34:29.061Z] Error: building at STEP "RUN ./server.sh $SCYLLA_PRODUCT_NAME $SCYLLA_VERSION $DRY_RUN $SCYLLA_REPO_FILE_URL": while running runtime: exit status 1
```
Failed on both release and debug,
Fixing it

server: fix rhel8 support

---

server

fix error:
```
01:20:37  Oracle Linux 8.10 is not supported by this installer.
01:20:37  Error: building at STEP "RUN ./server.sh $SCYLLA_PRODUCT_NAME $SCYLLA_VERSION $DRY_RUN $SCYLLA_REPO_FILE_URL": while running runtime: exit status 1
```
Failed jobs:
jenkins.scylladb.com/job/scylla-master/job/centos-rpm/1399/
https://jenkins.scylladb.com/job/scylla-6.0/job/centos-rpm/5/

server: fix Oracle Linux 8.10 support

---

.github/workflows/test.yml
README.md
server

includes the following changes:
1) as `debian10` and `centos7` reached EOL, removing it
2) align releases version (5.2.0, 2022.1, 2022.2 - removed / 6.0.0 - added)
3) adding `rockylinux:9` support (skip only in case 2023.1)
4) removing installation of `curl` package in test.yaml as for
debian/ubuntu it is part of the server script and for rpm it is part of minimal image
5) test.yml - Install packages and Scylla for `amazonlinux:2023` for only current supported version `6.0.0`
6) update `README.md` file accordingly

web-install: remove EOL OS + align release versions

---

server

Adding a new GPG key in RSA format which supports both deb and rpm signing
Related to scylladb/scylla-enterprise#4222

gpg: add the 2024 pub key (RSA)

---

.github/workflows/test.yml

as first GA of 2024.2.0 already released.
adding this version to test.yml to run ci tests on this version as well

test.yml: adding 2024.2.0 to ci web-install tests

---

.github/workflows/test.yml
server

As it's 1:1 binary-compatible with RHEL 9 and CentOS Stream 9
Also, fixing the unit tests to match the updated releases we have and
support
Fixes: https://github.com/scylladb/scylladb/issues/23583
```
[yaronkaikov@london]~/git/scylla-web-install (main)$ podman run -it --rm -v /home/yaronkaikov/git/scylla-web-install/:/scylla-web-install -w /scylla-web-install almalinux
[root@4b8d253ec742 scylla-web-install]# curl -sSf get.scylladb.com/server | bash
Operating system 'almalinux' is not supported by this installer.
[root@4b8d253ec742 scylla-web-install]# ./server 
Installing Scylla version 2025.1.0 for CentOS ...
Importing GPG key 0x7BAC99E3:
Userid     : "ScyllaDB Package Signing Key 2024 (RSA) <security@scylladb.com>"
Fingerprint: 4556 21E3 82DF B3E5 6B0C FBDB A43E 0665 7BAC 99E3
From …
```

server: add support for `almalinux` installation and adjust tests to match latest releases

---

.github/workflows/update_jira_status_ready_for_merge.yml

When a PR is added with the 'status/merge_candidate' label, then the relevant Jira ticket status will change to 'Ready For Merge'

Create update_jira_status_ready_for_merge.yml - Jira status automation
